// Static fallback portfolio data — Stage 4 can swap fetch from Sanity / Cloudinary.
// Categories must match filtering strings exactly.

export const portfolioCategories = [
  'All',
  'Posters',
  'Flyer Designs',
  'Brochure Designs',
  'Standee Designs',
  'Business Cards',
  'Logos',
  'Reels / Shorts',
  'YouTube',
  'Social Media',
  'Branding',
];

/**
 * mediaKind drives mockup visuals + lightbox behaviour.
 * aspectHint is used when aligning cards (square / poster / a4 …).
 */
export const portfolioItems = [
  // Posters
  {
    id: 101,
    title: 'Synthwave Nights — Venue Poster',
    category: 'Posters',
    mediaKind: 'poster',
    accent: '#ff4d8d',
    base: '#0d0612',
    blurb: 'Print-first event poster layout with bleed guides and typography lockup.',
    aspectHint: 'poster',
  },
  {
    id: 102,
    title: 'Film Club — Quarterly Key Art',
    category: 'Posters',
    mediaKind: 'poster',
    accent: '#6ee7ff',
    base: '#050a14',
    blurb: 'Cinematic palette study for limited-run auditorium prints.',
    aspectHint: 'poster',
  },
  {
    id: 103,
    title: 'Maker Fair — Illustrated Poster',
    category: 'Posters',
    mediaKind: 'poster',
    accent: '#c4ff4a',
    base: '#0b1008',
    blurb: 'Illustrative hero artwork with analogue texture overlay.',
    aspectHint: 'poster',
  },
  // Flyers
  {
    id: 201,
    title: 'Fashion Pop-up — A4 Announcement',
    category: 'Flyer Designs',
    mediaKind: 'flyer',
    accent: '#e94560',
    base: '#10080c',
    blurb: 'Single-sided A4 handout with restrained grid and serif headline.',
    aspectHint: 'a4',
  },
  {
    id: 202,
    title: 'Workshop Series — Portrait Flyer',
    category: 'Flyer Designs',
    mediaKind: 'flyer',
    accent: '#a78bfa',
    base: '#0c0a14',
    blurb: 'Portrait flyer stack for sequential session promotion.',
    aspectHint: 'a4',
  },
  // Brochures (PDF)
  {
    id: 301,
    title: 'Hospitality Group — Offer Booklet',
    category: 'Brochure Designs',
    mediaKind: 'brochure',
    accent: '#fbbf24',
    base: '#0f0d08',
    blurb: 'Multi-page booklet with curated photography and restrained type.',
    pdfUrl: 'https://www.w3.org/WAI/WCAG21/Techniques/pdf/img/table-word.pdf',
    aspectHint: 'document',
  },
  {
    id: 302,
    title: 'Tech Summit — Sponsor Brochure',
    category: 'Brochure Designs',
    mediaKind: 'brochure',
    accent: '#38bdf8',
    base: '#060c12',
    blurb: 'Conference sponsor overview with bold section dividers.',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    aspectHint: 'document',
  },
  // Standee
  {
    id: 401,
    title: 'Retail Launch — Floor Standee',
    category: 'Standee Designs',
    mediaKind: 'standee',
    accent: '#fb7185',
    base: '#14060a',
    blurb: 'Tall retail standee with vertical rhythm and brand lockup.',
    aspectHint: 'standee',
  },
  {
    id: 402,
    title: 'Café Seasonal — Counter Display',
    category: 'Standee Designs',
    mediaKind: 'standee',
    accent: '#34d399',
    base: '#07120c',
    blurb: 'Seasonal menu board treatment for QSR-style outlets.',
    aspectHint: 'standee',
  },
  // Business cards
  {
    id: 501,
    title: 'Studio Monogram — Card Pair',
    category: 'Business Cards',
    mediaKind: 'businessCard',
    accent: '#e94560',
    base: '#0a0a0a',
    cardFront: '#121212',
    cardBack: '#1c1014',
    blurb: 'Raised logomark on front, contact micro-type on reverse.',
    aspectHint: 'card',
  },
  {
    id: 502,
    title: 'Freelance Creative — Card Pair',
    category: 'Business Cards',
    mediaKind: 'businessCard',
    accent: '#93c5fd',
    base: '#080c12',
    cardFront: '#0f141c',
    cardBack: '#141c24',
    blurb: 'Minimal front with duotone edge; QR and socials on back.',
    aspectHint: 'card',
  },
  // Logos
  {
    id: 601,
    title: 'Audio Lab — Wordmark System',
    category: 'Logos',
    mediaKind: 'logo',
    accent: '#f472b6',
    base: '#0c080e',
    blurb: 'Responsive wordmark with mono lockup for product UI.',
    aspectHint: 'logo',
  },
  {
    id: 602,
    title: 'Trail Co. — Outdoor Mark',
    category: 'Logos',
    mediaKind: 'logo',
    accent: '#86efac',
    base: '#08100a',
    blurb: 'Geometric mark designed for embroidery and small-app icons.',
    aspectHint: 'logo',
  },
  // Reels / Shorts
  {
    id: 701,
    title: 'Product Tease — Vertical Cut',
    category: 'Reels / Shorts',
    mediaKind: 'reel',
    accent: '#a5b4fc',
    base: '#080818',
    videoSrc: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    blurb: 'Fast-cut vertical spot with kinetic type and product hero.',
    aspectHint: 'reel',
  },
  {
    id: 702,
    title: 'Event Hype — Social Reel',
    category: 'Reels / Shorts',
    mediaKind: 'reel',
    accent: '#fcd34d',
    base: '#120c04',
    videoSrc: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    blurb: 'Rhythm-led motion storyboard for launch week.',
    aspectHint: 'reel',
  },
  // YouTube
  {
    id: 801,
    title: 'Brand Film — Director Cut',
    category: 'YouTube',
    mediaKind: 'youtube',
    accent: '#f87171',
    base: '#120808',
    youtubeId: 'LXb3EKWsInQ',
    blurb: 'Long-form brand narrative with chapter pacing and sound design.',
    aspectHint: 'youtube',
  },
  {
    id: 802,
    title: 'Tutorial Series — Title Package',
    category: 'YouTube',
    mediaKind: 'youtube',
    accent: '#5eead4',
    base: '#061210',
    youtubeId: 'sPyCI93KvjE',
    blurb: 'Modular lower-thirds and intro sting for educational content.',
    aspectHint: 'youtube',
  },
  // Social
  {
    id: 901,
    title: 'Campaign Grid — Spring Drop',
    category: 'Social Media',
    mediaKind: 'social',
    accent: '#fda4af',
    base: '#10060a',
    blurb: 'Carousel-first grid with consistent colour tokens.',
    aspectHint: 'social',
  },
  {
    id: 902,
    title: 'Stories Pack — Product Focus',
    category: 'Social Media',
    mediaKind: 'social',
    accent: '#7dd3fc',
    base: '#040c12',
    blurb: 'Nine-panel story sequence with typographic hooks.',
    aspectHint: 'social',
  },
  // Branding
  {
    id: 1001,
    title: 'Boutique Hotel — Identity Kit',
    category: 'Branding',
    mediaKind: 'brand',
    accent: '#d4a574',
    base: '#0f0c08',
    blurb: 'Logo, colour, and pattern system for boutique hospitality.',
    aspectHint: 'brand',
  },
  {
    id: 1002,
    title: 'Dev Tooling — Visual Language',
    category: 'Branding',
    mediaKind: 'brand',
    accent: '#94a3b8',
    base: '#080a0c',
    blurb: 'Geometric language for product marketing and conference swag.',
    aspectHint: 'brand',
  },
];


